import { TranslationMessages } from 'ra-core';
const banglaMessages: TranslationMessages = {
    ra: {
        action: {
            add_filter: 'ফিল্টার যোগ করুন',
            add: 'যোগ করুন',
            back: 'পিছনে যান',
            bulk_actions: 'একটি আইটেম নির্বাচন করা হয়েছে |||| %{smart_count}টি আইটেম নির্বাচন করা হয়েছে',
            cancel: 'বাতিল',
            clear_array_input: 'তালিকা সাফ করুন',
            clear_input_value: 'মান সাফ করুন',
            clone: 'ক্লোন করুন',
            confirm: 'নিশ্চিত করুন',
            create: 'তৈরি করুন',
            create_item: '%{item} তৈরি করুন',
            delete: 'মুছে ফেলুন',
            edit: 'সম্পাদনা করুন',
            export: 'রপ্তানি করুন',
            list: 'তালিকা',
            refresh: 'রিফ্রেশ করুন',
            remove_filter: 'ফিল্টার সরান',
            remove_all_filters: 'সব ফিল্টার সরান',
            remove: 'সরান',
            save: 'সংরক্ষণ করুন',
            search: 'অনুসন্ধান',
            select_all: 'সব নির্বাচন করুন',
            select_row: 'এই সারি নির্বাচন করুন',
            show: 'দেখান',
            sort: 'সাজান',
            undo: 'ক্রিয়া প্রত্যাহার',
            unselect: 'বাছাই বাতিল',
            expand: 'সম্পূর্ণ দেখান',
            close: 'বন্ধ করুন',
            open_menu: 'মেনু খুলুন',
            close_menu: 'মেনু বন্ধ করুন',
            update: 'আপডেট করুন',
            move_up: 'উপরে সরান',
            move_down: 'নিচে সরান',
            open: 'খুলুন',
            toggle_theme: 'থিম পরিবর্তন করুন',
            select_columns: 'কলাম নির্বাচন করুন',
        },
        boolean: {
            true: 'হ্যাঁ',
            false: 'না',
            null: ' ',
        },
        page: {
            create: '%{name} তৈরি করুন',
            dashboard: 'ড্যাশবোর্ড',
            edit: '%{recordRepresentation} সম্পাদনা করুন',
            error: 'কিছু ভুল হয়েছে',
            list: '%{name}',
            loading: 'লোড হচ্ছে',
            not_found: 'পাওয়া যায়নি',
            show: '%{recordRepresentation} দেখান',
            empty: 'এখনও কোনো %{name} নেই',
            invite: 'আপনি কি একটি যোগ করতে চান?',
        },
        input: {
            file: {
                upload_several: 'আপলোড করার জন্য কিছু ফাইল ড্রপ করুন বা ক্লিক করুন',
                upload_single: 'আপলোড করার জন্য একটি ফাইল ড্রপ করুন বা ক্লিক করুন',
            },
            image: {
                upload_several: 'আপলোড করার জন্য কিছু ছবি ড্রপ করুন বা ক্লিক করুন',
                upload_single: 'আপলোড করার জন্য একটি ছবি ড্রপ করুন বা ক্লিক করুন',
            },
            references: {
                all_missing: 'রেফারেন্স ডেটা খুঁজে পাওয়া যাচ্ছে না',
                many_missing: 'এসোসিয়েটেড রেফারেন্সের কমপক্ষে একটি উপস্থিত নেই',
                single_missing: 'এসোসিয়েটেড রেফারেন্স আর উপস্থিত নেই',
            },
            password: {
                toggle_visible: 'পাসওয়ার্ড লুকান',
                toggle_hidden: 'পাসওয়ার্ড দেখান',
            },
        },
        message: {
            about: 'সম্পর্কে',
            are_you_sure: 'আপনি কি নিশ্চিত?',
            auth_error: 'অনুমোদন টোকেন যাচাই করার সময় একটি ত্রুটি হয়েছে।',
            bulk_delete_content:
                'আপনি কি নিশ্চিত যে আপনি এই %{name} মুছে ফেলতে চান? |||| আপনি কি নিশ্চিত যে আপনি এই %{smart_count}টি আইটেম মুছে ফেলতে চান?',
            bulk_delete_title:
                'মুছে ফেলুন %{name} |||| মুছে ফেলুন %{smart_count}টি %{name}',
            bulk_update_content:
                'আপনি কি নিশ্চিত যে আপনি এই %{name} আপডেট করতে চান? |||| আপনি কি নিশ্চিত যে আপনি এই %{smart_count}টি আইটেম আপডেট করতে চান?',
            bulk_update_title:
                'আপডেট করুন %{name} |||| আপডেট করুন %{smart_count}টি %{name}',
            clear_array_input: 'আপনি কি নিশ্চিত যে আপনি সম্পূর্ণ তালিকা পরিষ্কার করতে চান?',
            delete_content: 'আপনি কি নিশ্চিত যে আপনি এই আইটেমটি মুছে ফেলতে চান?',
            delete_title: 'মুছে ফেলুন %{name} #%{id}',
            details: 'বিবরণ',
            error: 'একটি ক্লায়েন্ট ত্রুটি হয়েছে এবং আপনার অনুরোধটি সম্পাদন করা যায়নি।',
            invalid_form: 'ফর্মটি সঠিক নয়। দয়া করে ভুল সংশোধন করুন।',
            loading: 'পৃষ্ঠা লোড হচ্ছে, দয়া করে অপেক্ষা করুন ...',
            no: 'না',
            not_found: 'আপলোড ত্রুটি হয়েছে অথবা আপনি যে পৃষ্ঠাটি অনুসন্ধান করছেন তা পাওয়া যায়নি।',
            yes: 'হ্যাঁ',
            unsaved_changes: 'কিছু আপডেট সংরক্ষণ করা হয়নি। আপনি কি নিশ্চিত যে আপনি এই পৃষ্ঠাটি ছেড়ে যেতে চান?',
        },
        navigation: {
            no_results: 'কোন ফলাফল পাওয়া যায়নি',
            no_more_results: 'পৃষ্ঠার বাইরে',
            page_out_of_boundaries: 'পৃষ্ঠা অবস্থান বাইরে',
            page_out_from_end: 'আমি সর্বাধিক পৃষ্ঠা থেকে এই পরে যেতে পারব না',
            page_out_from_begin: 'আমি প্রথম পৃষ্ঠাতে যেতে পারব না',
            page_range_info: '%{offsetBegin}-%{offsetEnd} থেকে %{total}',
            page_rows_per_page: 'প্রতি পৃষ্ঠায় সারি সংখ্যা:',
            next: 'পরবর্তী',
            previous: 'পূর্ববর্তী',
            skip_nav: 'মুখ্য বিষয়বস্তু এক্সেস করুন',
            partial_page_range_info:
                '%{offsetEnd} এর চেয়ে %{offsetBegin}-%{offsetEnd} বেশি',
            current_page: 'পৃষ্ঠা %{page}',
            page: '%{page} পৃষ্ঠায় যান',
            first: 'প্রথম পৃষ্ঠায় যান',
            last: 'শেষ পৃষ্ঠায় যান',
        },
        sort: {
            sort_by: 'দ্বারা সাজান:',
            ASC: 'একত্রেকৃত',
            DESC: 'অবক্রমিত',
        },
        auth: {
            auth_check_error: 'লগ ইন করার সময় সমস্যা হয়েছে, দয়া করে পুনঃচেষ্টা করুন।',
            user_menu: 'প্রোফাইল',
            username: 'ব্যবহারকারীর নাম',
            password: 'পাসওয়ার্ড',
            sign_in: 'সাইন ইন করুন',
            sign_in_error: 'লগ ইন করার সময় ত্রুটি হয়েছে, দয়া করে পুনঃচেষ্টা করুন।',
            logout: 'লগ আউট',
        },
        notification: {
            updated: 'আইটেম আপডেট হয়েছে |||| %{smart_count}টি আইটেম আপডেট হয়েছে',
            created: 'আইটেম তৈরি হয়েছে',
            deleted: 'আইটেম মুছে ফেলা হয়েছে |||| %{smart_count}টি আইটেম মুছে ফেলা হয়েছে',
            bad_item: 'ত্রুটিপূর্ণ আইটেম',
            item_doesnt_exist: 'আইটেমটি বিদ্যমান নেই',
            http_error: 'সার্ভার ত্রুটি',
            data_provider_error: 'ডেটা সরবরাহকারী ত্রুটি। বিবরণটি কনসোলে দেখুন।',
            canceled: 'কার্যক্রম বাতিল করা হয়েছে',
            logged_out: 'আপনি আউট হয়েছেন, দয়া করে পুনঃলগিন করুন।',
            i18n_error: 'আপনার নির্বাচিত ভাষায় অনুবাদ লোড করতে ব্যর্থ হয়েছে',
            not_authorized : 'আপনি অনুমোদিত নন',
        },
        validation: {
            required: 'আবশ্যক',
            minLength: 'কমপক্ষে%{min} অক্ষর হতে হবে',
            maxLength: 'সর্বাধিক%{max} অক্ষর হতে হবে',
            minValue: 'অন্তত হতে হবে%{min}',
            maxValue: 'সর্বাধিক হতে হবে%{max}',
            number: 'একটি সংখ্যা হতে হবে',
            email: 'একটি বৈধ ইমেল হতে হবে',
            oneOf: 'একটি নির্বাচিত মান হতে হবে: %{options}',
            regex: 'একটি নির্দিষ্ট ফর্ম্যাটে হতে হবে (regexp): %{pattern}',
        },
        saved_queries: {
            label: 'সংরক্ষিত অনুসন্ধান',
            query_name: 'অনুসন্ধান নাম',
            new_label: 'বর্তমান অনুসন্ধান সংরক্ষণ করুন...',
            new_dialog_title: 'ভিন্ন আকারে বর্তমান অনুসন্ধান সংরক্ষণ করুন',
            remove_label: 'সংরক্ষিত অনুসন্ধান সরান',
            remove_label_with_name: '"%{name}" সংরক্ষিত অনুসন্ধান সরান',
            remove_dialog_title: 'সংরক্ষিত অনুসন্ধান সরাবেন?',
            remove_message:
                'আপনি কি নিশ্চিত যে আপনি আপনার সংরক্ষিত অনুসন্ধানের তালিকা হতে এটি সরাতে চান?',
            help: 'তালিকা ফিল্টার করুন এবং পরবর্তীতে ব্যবহারের জন্য অনুসন্ধান সংরক্ষণ করুন',
        },
        configurable: {
            customize: 'কাস্টমাইজ করুন',
            configureMode: 'এই পৃষ্ঠাটি কনফিগার করুন',
            inspector: {
                title: 'ইন্সপেক্টর',
                content: 'এপ্লিকেশনের ইউ আই এর উপরে মাউস রেখে কনফিগার করুন',
                reset: 'পূর্বনির্ধারিত অবস্থায় ফিরে যান',
                hideAll: 'সব লুকান',
                showAll: 'সব দেখান',
            },
            Datagrid: {
                title: 'তথ্যছক',
                unlabeled: 'লেবেলহীন কলাম #%{column}',
            },
            SimpleForm: {
                title: 'ফরম',
                unlabeled: 'লেবেলহীন ইনপুট #%{input}',
            },
            SimpleList: {
                title: 'তালিকা',
                primaryText: 'মূখ্য লেখা',
                secondaryText: 'মাধ্যমিক লেখা',
                tertiaryText: 'গৌণ লেখা',
            },
        },
    },
};

export default banglaMessages;